# Generated by Django 5.2.1 on 2025-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmessage',
            name='message',
            field=models.TextField(default='Placeholder message', max_length=2000),
            preserve_default=False,
        ),
    ]
